apiVersion: sources.eventing.knative.dev/v1alpha1
kind: PrometheusSource
metadata:
  name: prometheus-source
spec:
  serverURL: https://prometheus-k8s.openshift-monitoring.svc:9091
  promQL: ALERTS
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
